import Head from 'next/head';
import About from '../components/About';
import Email from '../components/Email';
import Gallery from '../components/Gallery';
import Hero from '../components/Hero';
import Services from '../components/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mello Canine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero />
      <About />
      <Services />
      <Gallery />
      <Email />
    </div>
  )
}
