import Head from 'next/head';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import { StyledEngineProvider } from '@mui/material/styles';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mello Canine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero />
    </div>
  )
}
